# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MIT

version: "2"
virtualmachines:
- name: kubernetes
  image: instruqt-hashicorp/consul-1-5-kubernetes-1-14-0
  shell: /usr/bin/start.sh
  machine_type: n1-standard-2
